# Generated by Django 5.2.6 on 2025-09-22 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('kpi_card', 'KPI Card'), ('chart', 'Chart'), ('table', 'Data Table'), ('activity_feed', 'Activity Feed'), ('quick_actions', 'Quick Actions'), ('calendar', 'Calendar'), ('notifications', 'Notifications'), ('tasks', 'Task List')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('doughnut', 'Doughnut Chart'), ('pie', 'Pie Chart'), ('area', 'Area Chart')], max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('query_config', models.JSONField(default=dict, help_text='Configuration for data queries')),
                ('display_config', models.JSONField(default=dict, help_text='Display settings and styling')),
                ('refresh_interval', models.PositiveIntegerField(default=30, help_text='Refresh interval in seconds')),
                ('roles', models.JSONField(default=list, help_text='User roles that can see this widget')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('target_roles', models.JSONField(default=list, help_text='Target user roles')),
                ('is_dismissible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_dismiss_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, help_text='Specific target users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('cache_data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key'], name='apps_dashbo_cache_k_626b47_idx'), models.Index(fields=['expires_at'], name='apps_dashbo_expires_e38376_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_value', models.JSONField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hour', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_name', 'date'], name='apps_dashbo_metric__01f387_idx'), models.Index(fields=['date'], name='apps_dashbo_date_f0cc06_idx')],
                'unique_together': {('metric_name', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='UserDashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(default=dict, help_text='Grid layout configuration')),
                ('widget_settings', models.JSONField(default=dict, help_text='Per-widget user preferences')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('auto_refresh_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_action', 'User Action'), ('system_event', 'System Event'), ('data_change', 'Data Change'), ('security_event', 'Security Event'), ('integration', 'External Integration')], default='user_action', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='apps_dashbo_timesta_5b202f_idx'), models.Index(fields=['user', 'timestamp'], name='apps_dashbo_user_id_b3ac94_idx'), models.Index(fields=['activity_type', 'timestamp'], name='apps_dashbo_activit_bbcbc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_view', models.CharField(max_length=100)),
                ('widget_interactions', models.JSONField(default=dict)),
                ('session_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='apps_dashbo_user_id_c39ca1_idx'), models.Index(fields=['timestamp'], name='apps_dashbo_timesta_e29089_idx')],
            },
        ),
    ]
