# Generated by Django 5.1.2 on 2024-10-30 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('chief_complaint', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_treatment', 'In Treatment'), ('stabilized', 'Stabilized'), ('transferred', 'Transferred'), ('discharged', 'Discharged')], default='waiting', max_length=20)),
                ('vital_signs', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('assigned_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Emergency Case',
                'verbose_name_plural': 'Emergency Cases',
                'ordering': ['-arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('treatment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('procedure', models.TextField()),
                ('medications', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='emergency.emergencycase')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Treatment',
                'verbose_name_plural': 'Emergency Treatments',
                'ordering': ['-treatment_time'],
            },
        ),
    ]
