# Generated by Django 5.1.2 on 2024-12-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emergencycase',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='emergencytreatment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emergencytreatment',
            name='modified_at',
        ),
    ]
