# Generated by Django 5.2.5 on 2025-08-26 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hospital display name', max_length=100)),
                ('subdomain', models.CharField(help_text='Subdomain for hospital access', max_length=100, unique=True)),
                ('db_name', models.CharField(help_text='Database name for this hospital', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Hospital logo', null=True, upload_to='hospital_logos/')),
                ('address', models.TextField(blank=True, help_text='Hospital address', null=True)),
                ('phone', models.CharField(blank=True, help_text='Hospital contact phone', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Hospital contact email', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Hospital website', null=True)),
                ('subscription_plan', models.CharField(choices=[('BASIC', 'Basic Plan - $99/month'), ('STANDARD', 'Standard Plan - $199/month'), ('PREMIUM', 'Premium Plan - $399/month'), ('ENTERPRISE', 'Enterprise Plan - $799/month')], default='BASIC', help_text='Subscription plan', max_length=20)),
                ('subscription_start_date', models.DateTimeField(help_text='Subscription start date')),
                ('subscription_end_date', models.DateTimeField(help_text='Subscription end date')),
                ('trial_end_date', models.DateTimeField(blank=True, help_text='Trial period end date', null=True)),
                ('is_trial', models.BooleanField(default=True, help_text='Whether hospital is in trial period')),
                ('max_users', models.IntegerField(default=10, help_text='Maximum users allowed')),
                ('max_patients', models.IntegerField(default=1000, help_text='Maximum patients allowed')),
                ('max_storage_gb', models.IntegerField(default=5, help_text='Storage limit in GB')),
                ('telemedicine_enabled', models.BooleanField(default=False, help_text='Enable telemedicine module')),
                ('laboratory_enabled', models.BooleanField(default=True, help_text='Enable laboratory module')),
                ('radiology_enabled', models.BooleanField(default=True, help_text='Enable radiology module')),
                ('pharmacy_enabled', models.BooleanField(default=True, help_text='Enable pharmacy module')),
                ('billing_enabled', models.BooleanField(default=True, help_text='Enable billing module')),
                ('ipd_enabled', models.BooleanField(default=False, help_text='Enable IPD module')),
                ('emergency_enabled', models.BooleanField(default=False, help_text='Enable emergency module')),
                ('is_active', models.BooleanField(default=True, help_text='Whether hospital is active')),
                ('is_suspended', models.BooleanField(default=False, help_text='Whether hospital is suspended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(help_text='Hospital administrator', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital Tenant',
                'verbose_name_plural': 'Hospital Tenants',
                'db_table': 'tenants_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HOSPITAL_ADMIN', 'Hospital Administrator'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('RADIOLOGIST', 'Radiologist'), ('ACCOUNTANT', 'Accountant'), ('STAFF', 'General Staff')], default='STAFF', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times user has accessed this hospital')),
                ('tenant', models.ForeignKey(help_text='Hospital this user has access to', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital Access',
                'verbose_name_plural': 'Hospital Access Records',
                'db_table': 'tenants_tenant_access',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
