# ZAIN HMS Version Information
# This file is automatically generated during release process

__version__ = "2.1.0"
__build_date__ = "2025-09-23T10:30:00Z"
__git_commit__ = "current-development"

# Version components
VERSION_MAJOR = 2
VERSION_MINOR = 1
VERSION_PATCH = 0

# Release information
RELEASE_NAME = "ZAIN HMS v2.1.0"
RELEASE_CODENAME = "September 2025 Release"

# Feature flags for this version
FEATURES = {
    'ai_clinical_support': True,
    'multi_tenant': True,
    'real_time_notifications': True,
    'mobile_responsive': True,
    'multi_language': True,
    'advanced_reporting': True,
    'emergency_management': True,
    'billing_system': True,
    'automatic_updates': True,
    'zero_downtime_deployment': True,
    'database_migration_safety': True,
    'maintenance_mode': True,
}

def get_version_info():
    """Get comprehensive version information"""
    return {
        'version': __version__,
        'build_date': __build_date__,
        'git_commit': __git_commit__,
        'release_name': RELEASE_NAME,
        'release_codename': RELEASE_CODENAME,
        'features': FEATURES,
    }

def check_feature(feature_name):
    """Check if a feature is enabled in this version"""
    return FEATURES.get(feature_name, False)

def get_version_tuple():
    """Get version as tuple for comparison"""
    return (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)