# Generated by Django 5.2.5 on 2025-08-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleconsultationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('meeting_room_id', models.CharField(max_length=100, unique=True)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('consultation_notes', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Teleconsultation Appointment',
                'verbose_name_plural': 'Teleconsultation Appointments',
                'db_table': 'telemedicine_teleconsultation',
            },
        ),
        migrations.CreateModel(
            name='VirtualWaitingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_joined', models.BooleanField(default=False)),
                ('doctor_joined', models.BooleanField(default=False)),
                ('patient_join_time', models.DateTimeField(blank=True, null=True)),
                ('doctor_join_time', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telemedicine.teleconsultationappointment')),
            ],
            options={
                'db_table': 'telemedicine_virtual_waiting_room',
            },
        ),
    ]
