# Generated by Django 5.2.6 on 2025-09-22 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('PATIENT', 'Patient Report'), ('APPOINTMENT', 'Appointment Report'), ('BILLING', 'Billing Report'), ('DOCTOR', 'Doctor Report'), ('DEPARTMENT', 'Department Report'), ('FINANCIAL', 'Financial Report'), ('INVENTORY', 'Inventory Report'), ('LABORATORY', 'Laboratory Report'), ('EMERGENCY', 'Emergency Report')], max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('PATIENT', 'Patient Report'), ('APPOINTMENT', 'Appointment Report'), ('BILLING', 'Billing Report'), ('DOCTOR', 'Doctor Report'), ('DEPARTMENT', 'Department Report'), ('FINANCIAL', 'Financial Report'), ('INVENTORY', 'Inventory Report'), ('LABORATORY', 'Laboratory Report'), ('EMERGENCY', 'Emergency Report')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('columns', models.JSONField(default=list)),
                ('default_filters', models.JSONField(default=dict)),
                ('chart_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
