# Generated by Django 5.2.6 on 2025-09-22 20:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('X_RAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('ULTRASOUND', 'Ultrasound'), ('MAMMOGRAPHY', 'Mammography'), ('FLUOROSCOPY', 'Fluoroscopy'), ('NUCLEAR', 'Nuclear Medicine'), ('PET', 'PET Scan'), ('DEXA', 'DEXA Scan')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('CALIBRATION', 'Calibration Due'), ('OUT_OF_ORDER', 'Out of Order'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('total_studies', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_instance_uid', models.CharField(blank=True, max_length=64, unique=True)),
                ('study_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modality', models.CharField(choices=[('X_RAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('ULTRASOUND', 'Ultrasound'), ('MAMMOGRAPHY', 'Mammography'), ('FLUOROSCOPY', 'Fluoroscopy'), ('NUCLEAR', 'Nuclear Medicine'), ('PET', 'PET Scan'), ('DEXA', 'DEXA Scan')], max_length=20)),
                ('body_part', models.CharField(blank=True, choices=[('HEAD', 'Head'), ('NECK', 'Neck'), ('CHEST', 'Chest'), ('ABDOMEN', 'Abdomen'), ('PELVIS', 'Pelvis'), ('SPINE', 'Spine'), ('UPPER_LIMB', 'Upper Limb'), ('LOWER_LIMB', 'Lower Limb'), ('WHOLE_BODY', 'Whole Body')], max_length=20)),
                ('technique', models.TextField(blank=True)),
                ('contrast_used', models.BooleanField(default=False)),
                ('contrast_agent', models.CharField(blank=True, max_length=100)),
                ('study_quality', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('ADEQUATE', 'Adequate'), ('POOR', 'Poor'), ('NON_DIAGNOSTIC', 'Non-diagnostic')], default='GOOD', max_length=20)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('dicom_storage_path', models.CharField(blank=True, max_length=500)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PRELIMINARY', 'Preliminary Report'), ('FINAL', 'Final Report'), ('AMENDED', 'Amended Report')], default='PENDING', max_length=20)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('critical_findings', models.TextField(blank=True)),
                ('critical_notified_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiologist_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='ImagingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='radiology/images/')),
                ('dicom_file', models.FileField(blank=True, null=True, upload_to='radiology/dicom/')),
                ('series_number', models.PositiveIntegerField(default=1)),
                ('instance_number', models.PositiveIntegerField(default=1)),
                ('slice_thickness', models.FloatField(blank=True, null=True)),
                ('window_center', models.IntegerField(blank=True, null=True)),
                ('window_width', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('view_position', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='radiology.imagingstudy')),
            ],
            options={
                'ordering': ['series_number', 'instance_number'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('serial_number', models.CharField(blank=True, help_text='Auto-generated serial number', max_length=50, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency'), ('STAT', 'STAT')], default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('clinical_history', models.TextField(blank=True)),
                ('clinical_indication', models.TextField(blank=True)),
                ('provisional_diagnosis', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_radiology_orders', to=settings.AUTH_USER_MODEL)),
                ('ordering_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_radiology_studies', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_orders', to='patients.patient')),
                ('radiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_radiology_studies', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_radiology_orders', to=settings.AUTH_USER_MODEL)),
                ('technologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_radiology_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laterality', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('BILATERAL', 'Bilateral'), ('NA', 'Not Applicable')], default='NA', max_length=20)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='radiology.radiologyorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='radiology.radiologyorderitem'),
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('modality', models.CharField(choices=[('X_RAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('ULTRASOUND', 'Ultrasound'), ('MAMMOGRAPHY', 'Mammography'), ('FLUOROSCOPY', 'Fluoroscopy'), ('NUCLEAR', 'Nuclear Medicine'), ('PET', 'PET Scan'), ('DEXA', 'DEXA Scan')], max_length=20)),
                ('body_part', models.CharField(blank=True, choices=[('HEAD', 'Head'), ('NECK', 'Neck'), ('CHEST', 'Chest'), ('ABDOMEN', 'Abdomen'), ('PELVIS', 'Pelvis'), ('SPINE', 'Spine'), ('UPPER_LIMB', 'Upper Limb'), ('LOWER_LIMB', 'Lower Limb'), ('WHOLE_BODY', 'Whole Body')], max_length=20)),
                ('preparation_instructions', models.TextField(blank=True, help_text='Instructions for patient preparation')),
                ('contrast_required', models.BooleanField(default=False)),
                ('fasting_required', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30)),
                ('reporting_time_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='radiologyorderitem',
            name='study_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiology.studytype'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['order_number'], name='radiology_r_order_n_a9f69f_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['patient'], name='radiology_r_patient_464195_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['ordering_doctor'], name='radiology_r_orderin_db149c_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['status'], name='radiology_r_status_c57cc6_idx'),
        ),
    ]
