# Generated by Django 5.2.6 on 2025-09-22 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('ANESTHESIOLOGY', 'Anesthesiology'), ('CARDIOLOGY', 'Cardiology'), ('CARDIOTHORACIC_SURGERY', 'Cardiothoracic Surgery'), ('DERMATOLOGY', 'Dermatology'), ('EMERGENCY_MEDICINE', 'Emergency Medicine'), ('ENDOCRINOLOGY', 'Endocrinology'), ('FAMILY_MEDICINE', 'Family Medicine'), ('GASTROENTEROLOGY', 'Gastroenterology'), ('GENERAL_MEDICINE', 'General Medicine'), ('GENERAL_SURGERY', 'General Surgery'), ('GERIATRICS', 'Geriatrics'), ('GYNECOLOGY', 'Gynecology'), ('HEMATOLOGY', 'Hematology'), ('INFECTIOUS_DISEASE', 'Infectious Disease'), ('INTERNAL_MEDICINE', 'Internal Medicine'), ('NEPHROLOGY', 'Nephrology'), ('NEUROLOGY', 'Neurology'), ('NEUROSURGERY', 'Neurosurgery'), ('OBSTETRICS', 'Obstetrics'), ('ONCOLOGY', 'Oncology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('ORTHOPEDICS', 'Orthopedics'), ('OTOLARYNGOLOGY', 'Otolaryngology (ENT)'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PLASTIC_SURGERY', 'Plastic Surgery'), ('PSYCHIATRY', 'Psychiatry'), ('PULMONOLOGY', 'Pulmonology'), ('RADIOLOGY', 'Radiology'), ('RHEUMATOLOGY', 'Rheumatology'), ('UROLOGY', 'Urology')], max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/doctors')),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('VACATION', 'Vacation'), ('SICK_LEAVE', 'Sick Leave'), ('CONFERENCE', 'Conference/Training'), ('EMERGENCY', 'Emergency Leave'), ('PERSONAL', 'Personal Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('contact_info', models.CharField(blank=True, help_text='Emergency contact during leave', max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('covering_doctor', models.ForeignKey(blank=True, help_text='Doctor covering during this leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_leaves', to='doctors.doctor')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Leave',
                'verbose_name_plural': 'Doctor Leaves',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start_time', models.TimeField(blank=True, help_text='Break/lunch start time', null=True)),
                ('break_end_time', models.TimeField(blank=True, help_text='Break/lunch end time', null=True)),
                ('max_patients', models.PositiveIntegerField(default=20, help_text='Maximum patients for this time slot')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Template',
                'verbose_name_plural': 'Schedule Templates',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('max_patients', models.PositiveIntegerField(default=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='doctors.scheduletemplate')),
            ],
            options={
                'verbose_name': 'Schedule Template Slot',
                'verbose_name_plural': 'Schedule Template Slots',
            },
        ),
    ]
